### ISSUE TITLE
Cluster trying to connect to master port 0

### ISSUE THREAD

**Issue by dudizimber** [FalkorDB/falkordb-omnistrate#181]
We see in the logs:
Connecting to MASTER 35.223.121.178:0

Not sure if the logs are wrong, or the port was lost somewhere.
Cluster Multi Zone
instance-xabhzk2yq

**Comment by MuhammadQadora** [comment]
# Accept connections on the specified port, default is 6379 (IANA #815344).
# If port 0 is specified Redis will not listen on a TCP socket.
port 6379
