### ISSUE TITLE
Add ability to upload config file for redis / falkordb module

### ISSUE THREAD

**Issue by dudizimber** [FalkorDB/falkordb-omnistrate#56]

**Comment by dudizimber** [comment]
@gkorland @AviAvni 
We discussed allowing users to upload their custom config file to change the database's parameters.
I was thinking about it, and I'm not sure it's a good idea to do that as a config file, since we could only validate this file when the server spins up, which takes several minutes, and then we'd have to make somehow the user know that the config file is invalid.

I'm thinking about 2 options:
- Adding all the extra configurations we allow as "extra" fields (where you need to "open" the advanced configuration). This would make the image script a bit harder to read and maintain, but it's the simplest option.
- Asking Omnistrate to add a new type of field "JSON", which we can pass in a schema that they can automatically validate.

**Comment by dudizimber** [comment]
@swilly22 Which configuration parameters do we want to allow users to change?

**Comment by swilly22** [comment]
This is what I think should be configurable by the user

- CACHE_SIZE
- NODE_CREATION_BUFFER
- MAX_QUEUED_QUERIES
- TIMEOUT_MAX
- TIMEOUT_DEFAULT
- RESULTSET_SIZE
- QUERY_MEM_CAPACITY

**Comment by AviAvni** [comment]
@swilly22 can you also add valid range of value?

**Comment by swilly22** [comment]
@AviAvni Sure, I've updated to former comment to include default values which I think are reasonable.

**Comment by dudizimber** [comment]
@swilly22 can you add also a minimum and maximum, please?

**Comment by swilly22** [comment]
@dudizimber, Original comment updated to include [min-max] ranges.
